/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp -a dbus_adaptor.h: org.cn180s.dbus.xml
 *
 * qdbusxml2cpp is Copyright (C) 2016 The Qt Company Ltd.
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#ifndef DBUS_ADAPTOR_H
#define DBUS_ADAPTOR_H

#include <QtCore/QObject>
#include <QtDBus/QtDBus>
QT_BEGIN_NAMESPACE
class QByteArray;
template<class T> class QList;
template<class Key, class Value> class QMap;
class QString;
class QStringList;
class QVariant;
QT_END_NAMESPACE

/*
 * Adaptor class for interface org.cn180s.dbus
 */
class DbusAdaptor: public QDBusAbstractAdaptor
{
    Q_OBJECT
    Q_CLASSINFO("D-Bus Interface", "org.cn180s.dbus")
    Q_CLASSINFO("D-Bus Introspection", ""
"  <interface name=\"org.cn180s.dbus\">\n"
"    <signal name=\"control\">\n"
"      <arg direction=\"out\" type=\"i\" name=\"cmd\"/>\n"
"      <arg direction=\"out\" type=\"s\" name=\"data\"/>\n"
"    </signal>\n"
"    <signal name=\"reply\">\n"
"      <arg direction=\"out\" type=\"i\" name=\"cmd\"/>\n"
"      <arg direction=\"out\" type=\"s\" name=\"data\"/>\n"
"    </signal>\n"
"    <signal name=\"replyList\">\n"
"      <arg direction=\"out\" type=\"i\" name=\"cmd\"/>\n"
"      <arg direction=\"out\" type=\"as\" name=\"data\"/>\n"
"      <annotation value=\"QStringList\" name=\"org.qtproject.QtDBus.QtTypeName.Out0\"/>\n"
"    </signal>\n"
"  </interface>\n"
        "")
public:
    DbusAdaptor(QObject *parent);
    virtual ~DbusAdaptor();

public: // PROPERTIES
public Q_SLOTS: // METHODS
Q_SIGNALS: // SIGNALS
    void control(int cmd, const QString &data);
    void reply(int cmd, const QString &data);
    void replyList(int cmd, const QStringList &data);
};

#endif
